# Generated by Django 5.0.7 on 2024-08-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
