# Generated by Django 5.0.7 on 2024-08-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_published_date_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
